### ISSUE TITLE
amino/def.h error while calling #include <amino.h>

### ISSUE THREAD

**Issue by mamurtaza88** [golems/amino#24]
I installed the amino library from git, following the standard procedure mentioned on http://amino.golems.org/installation.html

After the installation, I verified amino installed as  /usr/local/include/amino-1.0 

I wrote a c++ code, which is calling amino library as follow:
#include <amino-1.0/amino.h>

This yields the following error:
/usr/local/include/amino-1.0/amino/la_impl.h:44:23: fatal error: amino/def.h: No such file or directory
 #include "amino/def.h"
                       ^
compilation terminated.

As per my understanding, it seems that this is the error on your end. Please do let me know if I had not followed the instruction properly.

Thanks

**Comment by ndantam** [comment]
Please set your CFLAGS / CPPFLAGS to add `/usr/local/include/amino-1.0/` to the include path.  The suggested/preferred way to do this is via pkg-config: 

    CPPFLAGS=`pkg-config --cflags amino`

If you are using autotools, try [PKG_CHECK_MODULES](https://autotools.io/pkgconfig/pkg_check_modules.html).

If you are using CMAKE, then [FindPkgConfig](https://cmake.org/cmake/help/v3.1/module/FindPkgConfig.html) seems to be the preferred approach.

**Comment by mamurtaza88** [comment]
Will running the command solve the issue? because currently it doesn't seem to work for me. I tried reinstalling it and passing it to the configure file but that also didnot solve the issue.

**Comment by ndantam** [comment]
You need to set the include path for your build system and compiler.  The specific command / syntax depends on your build system.

**Comment by mxgrey** [comment]
@mamurtaza88 It sounds like you're trying to compile your code without using a build system. The C and C++ languages are notoriously difficult to compile manually, so a build system is widely considered necessary for doing any useful work in those languages.

You can find a discussion on choosing a build system [here](https://stackoverflow.com/questions/12017580/c-build-systems-what-to-use).

**Comment by ndantam** [comment]
I just added a couple example build scripts (Make and CMake).  Please see these for details on using pkg-config to set the include path: https://github.com/golems/amino/tree/master/demo/build-script

**Comment by mamurtaza88** [comment]
Thank you @ndantam and @mxgrey , I got it working. Really appreciate the help.
