### ISSUE TITLE
Error during make

### ISSUE THREAD

**Issue by 1729antony** [golems/amino#26]
During make, I am getting the following error. Can you help me resolve this. 
--------------------------------------------------------------------------------------------------------- 
CCLD     aarx-view
./.libs/libamino.so: undefined reference to `aa_rx_ik_opt_err_qlnpv'
collect2: error: ld returned 1 exit status
Makefile:2513: recipe for target 'aarx-view' failed
make[2]: *** [aarx-view] Error 1
make[2]: Leaving directory '/home/asus/TM-kit/amino'
Makefile:3755: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/asus/TM-kit/amino'
Makefile:1985: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by ndantam** [comment]
Try installing nlopt and re-configure.

**Comment by ndantam** [comment]
I reproduced your error when NLopt is not installed.  We get enough of a performance improvement from this library that I think a strict dependency is appropriate.  I added a hard check at configure-time for NLopt in 57e828b4437cea410c197ddc250be5143378f015.

If installing NLopt does not fix your problem, please reopen.

**Comment by 1729antony** [comment]
Installing NLopt fixed it. Thanks!
