### ISSUE TITLE
undefined reference to 'aa_rx_wf_mtl_parse'

### ISSUE THREAD

**Issue by pbustos** [golems/amino#27]
Hello, I am getting this error in Ubuntu 18.04 with all dependencies installed. It looks like the object is not included in libamino.so but I cannot find the cause.

src/test/wavefront_test.o: In function `main':
/home/pbustos/software/amino/src/test/wavefront_test.c:15: undefined reference to `aa_rx_wf_parse'
./.libs/libamino.so: undefined reference to `aa_rx_wf_mtl_parse'
collect2: error: ld returned 1 exit status

Thanks

**Comment by ndantam** [comment]
The function `aa_rx_wf_parse` is defined in `src/wavefront/wavefront.c`, which is generated via lex/flex from `src/wavefront/wavefront.l`.  Libamino.so includes `src/wavefront/wavefront.c` in its sources list, so there *shouldn't* be a way to miss this function.  Could you please (double) check:

1. Whether you have lex/flex installed
2. Whether `src/wavefront/wavefront.c` is generated
3. Any errors are shown in config.log (please post, if you can)
4. Output of `nm -g .libs/libamino.so` to see if symbol `aa_rx_wf_parse` somehow was C++-name-mangled

**Comment by pbustos** [comment]
Thanks for the answer. 
I could see that workflow.c is generated but empty and the symbol is not in libamino.so (only the xxxfloat version)

The files you request.

--- config.log  
[config.log](https://github.com/golems/amino/files/3613003/config.log)
-- nm
[nm.txt](https://github.com/golems/amino/files/3613004/nm.txt)

**Comment by ndantam** [comment]
Seems that you may be missing a needed shared library for flex.  In our travis-CI tests, we install the `flex` package on Ubuntu bionic.  You can see the full package list and steps in `script/docker/ubuntu-bionic`.  Please check that you have flex installed and maybe try manually running it on `src/wavefront/wavefront.l` to see if it correctly generates the code.

From config.log, line 750:

    configure:23162: checking for flex
    configure:23178: found /usr/bin/flex
    configure:23189: result: flex
    configure:23227: flex conftest.l
    configure:23231: $? = 0
    configure:23233: checking lex output file root
    configure:23247: result: lex.yy
    configure:23252: checking lex library
    configure:23266: gcc -o conftest -g -O2   conftest.c   >&5
    /tmp/ccLV7pT8.o: In function `input':
    /home/pbustos/software/amino/lex.yy.c:1180: undefined reference to `yywrap'
    /tmp/ccLV7pT8.o: In function `yylex':
    /home/pbustos/software/amino/lex.yy.c:871: undefined reference to `yywrap'
    /tmp/ccLV7pT8.o: In function `main':
    /home/pbustos/software/amino/conftest.l:17: undefined reference to `yywrap'
    collect2: error: ld returned 1 exit status

**Comment by pbustos** [comment]
I double checked the list and I was missing f2c and groff.
flex now generates the wavefront.c file
[wavefront.c.pdf](https://github.com/golems/amino/files/3613591/wavefront.c.pdf)
and aa_rx_wf_parse seems to be there:

but now the aa_rx_wf_mtl_parse is missing in wavefront.c and libamino.so

I understand that mtl is OBJ materials format.



Searching in  libamino.so:

pbustos@robex:~/software/amino$ nm -g .libs/libamino.so | grep aa_rx_wf_mtl_parse
                 U aa_rx_wf_mtl_parse

**Comment by ndantam** [comment]
Function `aa_rx_wf_mtl_parse` is similarly generated via flex from `src/wavefront/mtl.l`.  If you also have an empty `src/wavefront/mtl.c`, you may need to delete it and re-`make` to get flex to generate a valid source file.

**Comment by pbustos** [comment]
Finally, it worked removing the empty mtl.c and regenerating it.

Thanks a lot

**Comment by ndantam** [comment]
Great!
